{"text": "2025-05-28T13:01:48.655093+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.282584", "seconds": 0.282584}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "run_service", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 191, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 343295, "name": "MainProcess"}, "thread": {"id": 134289898332288, "name": "MainThread"}, "time": {"repr": "2025-05-28 13:01:48.655093+07:00", "timestamp": 1748412108.655093}}}
{"text": "2025-05-28T13:01:58.018761+0700 INFO Method \"Solve\" has called from  |  ipv4:127.0.0.1:36852\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}\n", "record": {"elapsed": {"repr": "0:00:09.646252", "seconds": 9.646252}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 119, "message": "Method \"Solve\" has called from  |  ipv4:127.0.0.1:36852\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}", "module": "service_math_solve", "name": "__main__", "process": {"id": 343295, "name": "MainProcess"}, "thread": {"id": 134288888538816, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 13:01:58.018761+07:00", "timestamp": 1748412118.018761}}}
{"text": "2025-05-28T13:01:58.094872+0700 DEBUG Checking if 22 + 23 + (44**2*2)/33 is an equation...\n", "record": {"elapsed": {"repr": "0:00:09.722363", "seconds": 9.722363}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_is_equation", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 104, "message": "Checking if 22 + 23 + (44**2*2)/33 is an equation...", "module": "service_math_solve", "name": "__main__", "process": {"id": 343295, "name": "MainProcess"}, "thread": {"id": 134288888538816, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 13:01:58.094872+07:00", "timestamp": 1748412118.094872}}}
{"text": "2025-05-28T13:01:58.095370+0700 DEBUG 22 + 23 + (44**2*2)/33 is not an equation.\n", "record": {"elapsed": {"repr": "0:00:09.722861", "seconds": 9.722861}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_is_equation", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 111, "message": "22 + 23 + (44**2*2)/33 is not an equation.", "module": "service_math_solve", "name": "__main__", "process": {"id": 343295, "name": "MainProcess"}, "thread": {"id": 134288888538816, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 13:01:58.095370+07:00", "timestamp": 1748412118.09537}}}
{"text": "2025-05-28T13:02:58.348981+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.256239", "seconds": 0.256239}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "run_service", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 187, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 343432, "name": "MainProcess"}, "thread": {"id": 136895481385088, "name": "MainThread"}, "time": {"repr": "2025-05-28 13:02:58.348981+07:00", "timestamp": 1748412178.348981}}}
{"text": "2025-05-28T14:47:46.757751+0700 CRITICAL Service crashed: module 'service_math_solve_pb2_grpc' has no attribute 'add_MathSolverServicer_to_server'\n", "record": {"elapsed": {"repr": "0:00:00.269176", "seconds": 0.269176}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "<module>", "level": {"icon": "‚ò†Ô∏è", "name": "CRITICAL", "no": 50}, "line": 206, "message": "Service crashed: module 'service_math_solve_pb2_grpc' has no attribute 'add_MathSolverServicer_to_server'", "module": "service_math_solve", "name": "__main__", "process": {"id": 398590, "name": "MainProcess"}, "thread": {"id": 138768162087040, "name": "MainThread"}, "time": {"repr": "2025-05-28 14:47:46.757751+07:00", "timestamp": 1748418466.757751}}}
{"text": "2025-05-28T14:48:34.139502+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.256772", "seconds": 0.256772}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 197, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 398658, "name": "MainProcess"}, "thread": {"id": 132371681013888, "name": "MainThread"}, "time": {"repr": "2025-05-28 14:48:34.139502+07:00", "timestamp": 1748418514.139502}}}
{"text": "2025-05-28T14:50:42.654729+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.267795", "seconds": 0.267795}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 197, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 398768, "name": "MainProcess"}, "thread": {"id": 129588919464064, "name": "MainThread"}, "time": {"repr": "2025-05-28 14:50:42.654729+07:00", "timestamp": 1748418642.654729}}}
{"text": "2025-05-28T14:51:00.509697+0700 INFO Method \"Solve\" has called from  |  ipv4:127.0.0.1:58468\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}\n", "record": {"elapsed": {"repr": "0:00:18.122763", "seconds": 18.122763}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 134, "message": "Method \"Solve\" has called from  |  ipv4:127.0.0.1:58468\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}", "module": "service_math_solve", "name": "__main__", "process": {"id": 398768, "name": "MainProcess"}, "thread": {"id": 129587778397888, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 14:51:00.509697+07:00", "timestamp": 1748418660.509697}}}
{"text": "2025-05-28T14:51:00.561904+0700 ERROR Solve error: name 'self' is not defined\n", "record": {"elapsed": {"repr": "0:00:18.174970", "seconds": 18.17497}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "Solve", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 180, "message": "Solve error: name 'self' is not defined", "module": "service_math_solve", "name": "__main__", "process": {"id": 398768, "name": "MainProcess"}, "thread": {"id": 129587778397888, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 14:51:00.561904+07:00", "timestamp": 1748418660.561904}}}
{"text": "2025-05-28T14:51:06.102464+0700 INFO Method \"Metadata\" has called from  |  ipv4:127.0.0.1:58468\n{}\n", "record": {"elapsed": {"repr": "0:00:23.715530", "seconds": 23.71553}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 134, "message": "Method \"Metadata\" has called from  |  ipv4:127.0.0.1:58468\n{}", "module": "service_math_solve", "name": "__main__", "process": {"id": 398768, "name": "MainProcess"}, "thread": {"id": 129587778397888, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 14:51:06.102464+07:00", "timestamp": 1748418666.102464}}}
{"text": "2025-05-28T14:51:11.660509+0700 INFO Method \"Solve\" has called from  |  ipv4:127.0.0.1:58468\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}\n", "record": {"elapsed": {"repr": "0:00:29.273575", "seconds": 29.273575}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 134, "message": "Method \"Solve\" has called from  |  ipv4:127.0.0.1:58468\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}", "module": "service_math_solve", "name": "__main__", "process": {"id": 398768, "name": "MainProcess"}, "thread": {"id": 129587778397888, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 14:51:11.660509+07:00", "timestamp": 1748418671.660509}}}
{"text": "2025-05-28T14:51:11.664657+0700 ERROR Solve error: name 'self' is not defined\n", "record": {"elapsed": {"repr": "0:00:29.277723", "seconds": 29.277723}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "Solve", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 180, "message": "Solve error: name 'self' is not defined", "module": "service_math_solve", "name": "__main__", "process": {"id": 398768, "name": "MainProcess"}, "thread": {"id": 129587778397888, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 14:51:11.664657+07:00", "timestamp": 1748418671.664657}}}
{"text": "2025-05-28T14:51:18.553252+0700 INFO Method \"Metadata\" has called from  |  ipv4:127.0.0.1:58468\n{}\n", "record": {"elapsed": {"repr": "0:00:36.166318", "seconds": 36.166318}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 134, "message": "Method \"Metadata\" has called from  |  ipv4:127.0.0.1:58468\n{}", "module": "service_math_solve", "name": "__main__", "process": {"id": 398768, "name": "MainProcess"}, "thread": {"id": 129587778397888, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 14:51:18.553252+07:00", "timestamp": 1748418678.553252}}}
{"text": "2025-05-28T14:52:12.935603+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.255382", "seconds": 0.255382}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 201, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 398943, "name": "MainProcess"}, "thread": {"id": 136057668964480, "name": "MainThread"}, "time": {"repr": "2025-05-28 14:52:12.935603+07:00", "timestamp": 1748418732.935603}}}
{"text": "2025-05-28T14:53:02.337011+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.255995", "seconds": 0.255995}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 199, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 399030, "name": "MainProcess"}, "thread": {"id": 136740028297344, "name": "MainThread"}, "time": {"repr": "2025-05-28 14:53:02.337011+07:00", "timestamp": 1748418782.337011}}}
{"text": "2025-05-28T14:53:45.767852+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.257885", "seconds": 0.257885}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 196, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 399103, "name": "MainProcess"}, "thread": {"id": 138162875641984, "name": "MainThread"}, "time": {"repr": "2025-05-28 14:53:45.767852+07:00", "timestamp": 1748418825.767852}}}
{"text": "2025-05-28T14:53:49.126987+0700 INFO Method \"Metadata\" has called from  |  ipv4:127.0.0.1:47990\n{}\n", "record": {"elapsed": {"repr": "0:00:03.617020", "seconds": 3.61702}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 133, "message": "Method \"Metadata\" has called from  |  ipv4:127.0.0.1:47990\n{}", "module": "service_math_solve", "name": "__main__", "process": {"id": 399103, "name": "MainProcess"}, "thread": {"id": 138161799796416, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 14:53:49.126987+07:00", "timestamp": 1748418829.126987}}}
{"text": "2025-05-28T14:53:54.821165+0700 INFO Method \"Solve\" has called from  |  ipv4:127.0.0.1:47990\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}\n", "record": {"elapsed": {"repr": "0:00:09.311198", "seconds": 9.311198}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 133, "message": "Method \"Solve\" has called from  |  ipv4:127.0.0.1:47990\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}", "module": "service_math_solve", "name": "__main__", "process": {"id": 399103, "name": "MainProcess"}, "thread": {"id": 138161799796416, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 14:53:54.821165+07:00", "timestamp": 1748418834.821165}}}
{"text": "2025-05-28T14:53:54.875204+0700 ERROR Solve error: name 'self' is not defined\n", "record": {"elapsed": {"repr": "0:00:09.365237", "seconds": 9.365237}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "Solve", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 179, "message": "Solve error: name 'self' is not defined", "module": "service_math_solve", "name": "__main__", "process": {"id": 399103, "name": "MainProcess"}, "thread": {"id": 138161799796416, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 14:53:54.875204+07:00", "timestamp": 1748418834.875204}}}
{"text": "2025-05-28T14:58:51.461665+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.256274", "seconds": 0.256274}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 195, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 399286, "name": "MainProcess"}, "thread": {"id": 139456639639680, "name": "MainThread"}, "time": {"repr": "2025-05-28 14:58:51.461665+07:00", "timestamp": 1748419131.461665}}}
{"text": "2025-05-28T14:58:54.802291+0700 INFO Method \"Solve\" has called from  |  ipv4:127.0.0.1:34424\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}\n", "record": {"elapsed": {"repr": "0:00:03.596900", "seconds": 3.5969}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 132, "message": "Method \"Solve\" has called from  |  ipv4:127.0.0.1:34424\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}", "module": "service_math_solve", "name": "__main__", "process": {"id": 399286, "name": "MainProcess"}, "thread": {"id": 139455088285376, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 14:58:54.802291+07:00", "timestamp": 1748419134.802291}}}
{"text": "2025-05-28T14:58:54.856325+0700 ERROR An error has been caught in function 'Solve', process 'MainProcess' (399286), thread 'ThreadPoolExecutor-0_0' (139455088285376):\nTraceback (most recent call last):\n\n  File \"/usr/lib/python3.12/threading.py\", line 1030, in _bootstrap\n    self._bootstrap_inner()\n    ‚îÇ    ‚îî <function Thread._bootstrap_inner at 0x7ed5c647a660>\n    ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 139455088285376)>\n  File \"/usr/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n    self.run()\n    ‚îÇ    ‚îî <function Thread.run at 0x7ed5c647a340>\n    ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 139455088285376)>\n  File \"/usr/lib/python3.12/threading.py\", line 1010, in run\n    self._target(*self._args, **self._kwargs)\n    ‚îÇ    ‚îÇ        ‚îÇ    ‚îÇ        ‚îÇ    ‚îî {}\n    ‚îÇ    ‚îÇ        ‚îÇ    ‚îÇ        ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 139455088285376)>\n    ‚îÇ    ‚îÇ        ‚îÇ    ‚îî (<weakref at 0x7ed5c344ad40; to 'ThreadPoolExecutor' at 0x7ed5c35a3230>, <_queue.SimpleQueue object at 0x7ed5c3a9bec0>, None,...\n    ‚îÇ    ‚îÇ        ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 139455088285376)>\n    ‚îÇ    ‚îî <function _worker at 0x7ed5c2ca47c0>\n    ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 139455088285376)>\n  File \"/usr/lib/python3.12/concurrent/futures/thread.py\", line 92, in _worker\n    work_item.run()\n    ‚îÇ         ‚îî <function _WorkItem.run at 0x7ed5c2ca5e40>\n    ‚îî <concurrent.futures.thread._WorkItem object at 0x7ed5c342da30>\n  File \"/usr/lib/python3.12/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ‚îÇ    ‚îÇ   ‚îÇ    ‚îÇ       ‚îÇ    ‚îî {}\n             ‚îÇ    ‚îÇ   ‚îÇ    ‚îÇ       ‚îî <concurrent.futures.thread._WorkItem object at 0x7ed5c342da30>\n             ‚îÇ    ‚îÇ   ‚îÇ    ‚îî (<function _unary_response_in_pool at 0x7ed5c2cdd120>, <grpc._cython.cygrpc.RequestCallEvent object at 0x7ed5c348c180>, <grpc...\n             ‚îÇ    ‚îÇ   ‚îî <concurrent.futures.thread._WorkItem object at 0x7ed5c342da30>\n             ‚îÇ    ‚îî <built-in method run of _contextvars.Context object at 0x7ed5c3947c40>\n             ‚îî <concurrent.futures.thread._WorkItem object at 0x7ed5c342da30>\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/.venv/lib/python3.12/site-packages/grpc/_server.py\", line 793, in _unary_response_in_pool\n    response, proceed = _call_behavior(\n                        ‚îî <function _call_behavior at 0x7ed5c2cdccc0>\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/.venv/lib/python3.12/site-packages/grpc/_server.py\", line 610, in _call_behavior\n    response_or_iterator = behavior(argument, context)\n                           ‚îÇ        ‚îÇ         ‚îî <grpc._server._Context object at 0x7ed5c2ce01d0>\n                           ‚îÇ        ‚îî expression: \"(23+44^2*2/33)+22\"\n                           ‚îÇ          \n                           ‚îî <bound method gRPC_math_solve.Solve of <__main__.gRPC_math_solve object at 0x7ed5c2c828d0>>\n\n> File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 168, in Solve\n    MathAnswer = MathSolver.SolveExpression(request)\n                 ‚îÇ          ‚îÇ               ‚îî expression: \"(23+44^2*2/33)+22\"\n                 ‚îÇ          ‚îÇ                 \n                 ‚îÇ          ‚îî <function MathSolver.SolveExpression at 0x7ed5c2df6d40>\n                 ‚îî <class '__main__.MathSolver'>\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 113, in SolveExpression\n    if self._is_equation(parsed):\n                         ‚îî 22 + 23 + (44**2*2)/33\n\nNameError: name 'self' is not defined\n", "record": {"elapsed": {"repr": "0:00:03.650934", "seconds": 3.650934}, "exception": {"type": "NameError", "value": "name 'self' is not defined", "traceback": true}, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "Solve", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 168, "message": "An error has been caught in function 'Solve', process 'MainProcess' (399286), thread 'ThreadPoolExecutor-0_0' (139455088285376):", "module": "service_math_solve", "name": "__main__", "process": {"id": 399286, "name": "MainProcess"}, "thread": {"id": 139455088285376, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 14:58:54.856325+07:00", "timestamp": 1748419134.856325}}}
{"text": "2025-05-28T15:00:51.869858+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.263275", "seconds": 0.263275}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 195, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 399447, "name": "MainProcess"}, "thread": {"id": 128261509247104, "name": "MainThread"}, "time": {"repr": "2025-05-28 15:00:51.869858+07:00", "timestamp": 1748419251.869858}}}
{"text": "2025-05-28T15:00:54.637610+0700 INFO Method \"Solve\" has called from  |  ipv4:127.0.0.1:39382\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}\n", "record": {"elapsed": {"repr": "0:00:03.031027", "seconds": 3.031027}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 132, "message": "Method \"Solve\" has called from  |  ipv4:127.0.0.1:39382\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}", "module": "service_math_solve", "name": "__main__", "process": {"id": 399447, "name": "MainProcess"}, "thread": {"id": 128260365067968, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 15:00:54.637610+07:00", "timestamp": 1748419254.63761}}}
{"text": "2025-05-28T15:00:54.637867+0700 ERROR An error has been caught in function 'Solve', process 'MainProcess' (399447), thread 'ThreadPoolExecutor-0_0' (128260365067968):\nTraceback (most recent call last):\n\n  File \"/usr/lib/python3.12/threading.py\", line 1030, in _bootstrap\n    self._bootstrap_inner()\n    ‚îÇ    ‚îî <function Thread._bootstrap_inner at 0x74a73481e660>\n    ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 128260365067968)>\n  File \"/usr/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n    self.run()\n    ‚îÇ    ‚îî <function Thread.run at 0x74a73481e340>\n    ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 128260365067968)>\n  File \"/usr/lib/python3.12/threading.py\", line 1010, in run\n    self._target(*self._args, **self._kwargs)\n    ‚îÇ    ‚îÇ        ‚îÇ    ‚îÇ        ‚îÇ    ‚îî {}\n    ‚îÇ    ‚îÇ        ‚îÇ    ‚îÇ        ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 128260365067968)>\n    ‚îÇ    ‚îÇ        ‚îÇ    ‚îî (<weakref at 0x74a731624e50; to 'ThreadPoolExecutor' at 0x74a7317c0e30>, <_queue.SimpleQueue object at 0x74a731ea0180>, None,...\n    ‚îÇ    ‚îÇ        ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 128260365067968)>\n    ‚îÇ    ‚îî <function _worker at 0x74a73106c7c0>\n    ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 128260365067968)>\n  File \"/usr/lib/python3.12/concurrent/futures/thread.py\", line 92, in _worker\n    work_item.run()\n    ‚îÇ         ‚îî <function _WorkItem.run at 0x74a73106de40>\n    ‚îî <concurrent.futures.thread._WorkItem object at 0x74a7310a42f0>\n  File \"/usr/lib/python3.12/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ‚îÇ    ‚îÇ   ‚îÇ    ‚îÇ       ‚îÇ    ‚îî {}\n             ‚îÇ    ‚îÇ   ‚îÇ    ‚îÇ       ‚îî <concurrent.futures.thread._WorkItem object at 0x74a7310a42f0>\n             ‚îÇ    ‚îÇ   ‚îÇ    ‚îî (<function _unary_response_in_pool at 0x74a7310a9120>, <grpc._cython.cygrpc.RequestCallEvent object at 0x74a7317e6d90>, <grpc...\n             ‚îÇ    ‚îÇ   ‚îî <concurrent.futures.thread._WorkItem object at 0x74a7310a42f0>\n             ‚îÇ    ‚îî <built-in method run of _contextvars.Context object at 0x74a731d97080>\n             ‚îî <concurrent.futures.thread._WorkItem object at 0x74a7310a42f0>\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/.venv/lib/python3.12/site-packages/grpc/_server.py\", line 793, in _unary_response_in_pool\n    response, proceed = _call_behavior(\n                        ‚îî <function _call_behavior at 0x74a7310a8cc0>\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/.venv/lib/python3.12/site-packages/grpc/_server.py\", line 610, in _call_behavior\n    response_or_iterator = behavior(argument, context)\n                           ‚îÇ        ‚îÇ         ‚îî <grpc._server._Context object at 0x74a7310a4560>\n                           ‚îÇ        ‚îî expression: \"(23+44^2*2/33)+22\"\n                           ‚îÇ          \n                           ‚îî <bound method gRPC_math_solve.Solve of <__main__.gRPC_math_solve object at 0x74a7319214c0>>\n\n> File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 168, in Solve\n    MathAnswer = MathSolver.SolveExpression(request)\n                 ‚îÇ          ‚îÇ               ‚îî expression: \"(23+44^2*2/33)+22\"\n                 ‚îÇ          ‚îÇ                 \n                 ‚îÇ          ‚îî <function MathSolver.SolveExpression at 0x74a730fc6d40>\n                 ‚îî <class '__main__.MathSolver'>\n\nTypeError: MathSolver.SolveExpression() missing 1 required positional argument: 'request'\n", "record": {"elapsed": {"repr": "0:00:03.031284", "seconds": 3.031284}, "exception": {"type": "TypeError", "value": "MathSolver.SolveExpression() missing 1 required positional argument: 'request'", "traceback": true}, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "Solve", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 168, "message": "An error has been caught in function 'Solve', process 'MainProcess' (399447), thread 'ThreadPoolExecutor-0_0' (128260365067968):", "module": "service_math_solve", "name": "__main__", "process": {"id": 399447, "name": "MainProcess"}, "thread": {"id": 128260365067968, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 15:00:54.637867+07:00", "timestamp": 1748419254.637867}}}
{"text": "2025-05-28T15:01:15.618898+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.260174", "seconds": 0.260174}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 195, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 399516, "name": "MainProcess"}, "thread": {"id": 131139519680640, "name": "MainThread"}, "time": {"repr": "2025-05-28 15:01:15.618898+07:00", "timestamp": 1748419275.618898}}}
{"text": "2025-05-28T15:01:18.712737+0700 INFO Method \"Solve\" has called from  |  ipv4:127.0.0.1:42962\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}\n", "record": {"elapsed": {"repr": "0:00:03.354013", "seconds": 3.354013}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 132, "message": "Method \"Solve\" has called from  |  ipv4:127.0.0.1:42962\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}", "module": "service_math_solve", "name": "__main__", "process": {"id": 399516, "name": "MainProcess"}, "thread": {"id": 131137833793216, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 15:01:18.712737+07:00", "timestamp": 1748419278.712737}}}
{"text": "2025-05-28T15:01:18.772448+0700 ERROR An error has been caught in function 'Solve', process 'MainProcess' (399516), thread 'ThreadPoolExecutor-0_0' (131137833793216):\nTraceback (most recent call last):\n\n  File \"/usr/lib/python3.12/threading.py\", line 1030, in _bootstrap\n    self._bootstrap_inner()\n    ‚îÇ    ‚îî <function Thread._bootstrap_inner at 0x77454b476660>\n    ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 131137833793216)>\n  File \"/usr/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n    self.run()\n    ‚îÇ    ‚îî <function Thread.run at 0x77454b476340>\n    ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 131137833793216)>\n  File \"/usr/lib/python3.12/threading.py\", line 1010, in run\n    self._target(*self._args, **self._kwargs)\n    ‚îÇ    ‚îÇ        ‚îÇ    ‚îÇ        ‚îÇ    ‚îî {}\n    ‚îÇ    ‚îÇ        ‚îÇ    ‚îÇ        ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 131137833793216)>\n    ‚îÇ    ‚îÇ        ‚îÇ    ‚îî (<weakref at 0x77454858b330; to 'ThreadPoolExecutor' at 0x774548582fc0>, <_queue.SimpleQueue object at 0x774547c63290>, None,...\n    ‚îÇ    ‚îÇ        ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 131137833793216)>\n    ‚îÇ    ‚îî <function _worker at 0x774547ca47c0>\n    ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 131137833793216)>\n  File \"/usr/lib/python3.12/concurrent/futures/thread.py\", line 92, in _worker\n    work_item.run()\n    ‚îÇ         ‚îî <function _WorkItem.run at 0x774547ca5e40>\n    ‚îî <concurrent.futures.thread._WorkItem object at 0x774548fe5e80>\n  File \"/usr/lib/python3.12/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ‚îÇ    ‚îÇ   ‚îÇ    ‚îÇ       ‚îÇ    ‚îî {}\n             ‚îÇ    ‚îÇ   ‚îÇ    ‚îÇ       ‚îî <concurrent.futures.thread._WorkItem object at 0x774548fe5e80>\n             ‚îÇ    ‚îÇ   ‚îÇ    ‚îî (<function _unary_response_in_pool at 0x774547ce1120>, <grpc._cython.cygrpc.RequestCallEvent object at 0x774548a1a110>, <grpc...\n             ‚îÇ    ‚îÇ   ‚îî <concurrent.futures.thread._WorkItem object at 0x774548fe5e80>\n             ‚îÇ    ‚îî <built-in method run of _contextvars.Context object at 0x77454898bf80>\n             ‚îî <concurrent.futures.thread._WorkItem object at 0x774548fe5e80>\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/.venv/lib/python3.12/site-packages/grpc/_server.py\", line 793, in _unary_response_in_pool\n    response, proceed = _call_behavior(\n                        ‚îî <function _call_behavior at 0x774547ce0cc0>\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/.venv/lib/python3.12/site-packages/grpc/_server.py\", line 610, in _call_behavior\n    response_or_iterator = behavior(argument, context)\n                           ‚îÇ        ‚îÇ         ‚îî <grpc._server._Context object at 0x774547cd4950>\n                           ‚îÇ        ‚îî expression: \"(23+44^2*2/33)+22\"\n                           ‚îÇ          \n                           ‚îî <bound method gRPC_math_solve.Solve of <__main__.gRPC_math_solve object at 0x774547cb0590>>\n\n> File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 168, in Solve\n    MathAnswer = MathSolver.SolveExpression(self, request)\n                 ‚îÇ          ‚îÇ               ‚îÇ     ‚îî expression: \"(23+44^2*2/33)+22\"\n                 ‚îÇ          ‚îÇ               ‚îÇ       \n                 ‚îÇ          ‚îÇ               ‚îî <__main__.gRPC_math_solve object at 0x774547cb0590>\n                 ‚îÇ          ‚îî <function MathSolver.SolveExpression at 0x774547df6d40>\n                 ‚îî <class '__main__.MathSolver'>\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 113, in SolveExpression\n    if self._is_equation(parsed):\n       ‚îÇ                 ‚îî 22 + 23 + (44**2*2)/33\n       ‚îî <__main__.gRPC_math_solve object at 0x774547cb0590>\n\nAttributeError: 'gRPC_math_solve' object has no attribute '_is_equation'\n", "record": {"elapsed": {"repr": "0:00:03.413724", "seconds": 3.413724}, "exception": {"type": "AttributeError", "value": "'gRPC_math_solve' object has no attribute '_is_equation'", "traceback": true}, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "Solve", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 168, "message": "An error has been caught in function 'Solve', process 'MainProcess' (399516), thread 'ThreadPoolExecutor-0_0' (131137833793216):", "module": "service_math_solve", "name": "__main__", "process": {"id": 399516, "name": "MainProcess"}, "thread": {"id": 131137833793216, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 15:01:18.772448+07:00", "timestamp": 1748419278.772448}}}
{"text": "2025-05-28T15:01:49.414902+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.259385", "seconds": 0.259385}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 195, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 399592, "name": "MainProcess"}, "thread": {"id": 127780115980416, "name": "MainThread"}, "time": {"repr": "2025-05-28 15:01:49.414902+07:00", "timestamp": 1748419309.414902}}}
{"text": "2025-05-28T15:01:51.559985+0700 INFO Method \"Solve\" has called from  |  ipv4:127.0.0.1:48644\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}\n", "record": {"elapsed": {"repr": "0:00:02.404468", "seconds": 2.404468}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 132, "message": "Method \"Solve\" has called from  |  ipv4:127.0.0.1:48644\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}", "module": "service_math_solve", "name": "__main__", "process": {"id": 399592, "name": "MainProcess"}, "thread": {"id": 127778431170240, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 15:01:51.559985+07:00", "timestamp": 1748419311.559985}}}
{"text": "2025-05-28T15:01:51.615308+0700 ERROR An error has been caught in function 'Solve', process 'MainProcess' (399592), thread 'ThreadPoolExecutor-0_0' (127778431170240):\nTraceback (most recent call last):\n\n  File \"/usr/lib/python3.12/threading.py\", line 1030, in _bootstrap\n    self._bootstrap_inner()\n    ‚îÇ    ‚îî <function Thread._bootstrap_inner at 0x74371f376660>\n    ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 127778431170240)>\n  File \"/usr/lib/python3.12/threading.py\", line 1073, in _bootstrap_inner\n    self.run()\n    ‚îÇ    ‚îî <function Thread.run at 0x74371f376340>\n    ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 127778431170240)>\n  File \"/usr/lib/python3.12/threading.py\", line 1010, in run\n    self._target(*self._args, **self._kwargs)\n    ‚îÇ    ‚îÇ        ‚îÇ    ‚îÇ        ‚îÇ    ‚îî {}\n    ‚îÇ    ‚îÇ        ‚îÇ    ‚îÇ        ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 127778431170240)>\n    ‚îÇ    ‚îÇ        ‚îÇ    ‚îî (<weakref at 0x74371bc1b600; to 'ThreadPoolExecutor' at 0x74371c022c90>, <_queue.SimpleQueue object at 0x74371ca240e0>, None,...\n    ‚îÇ    ‚îÇ        ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 127778431170240)>\n    ‚îÇ    ‚îî <function _worker at 0x74371bbf07c0>\n    ‚îî <Thread(ThreadPoolExecutor-0_0, started daemon 127778431170240)>\n  File \"/usr/lib/python3.12/concurrent/futures/thread.py\", line 92, in _worker\n    work_item.run()\n    ‚îÇ         ‚îî <function _WorkItem.run at 0x74371bbf1e40>\n    ‚îî <concurrent.futures.thread._WorkItem object at 0x74371bc20680>\n  File \"/usr/lib/python3.12/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ‚îÇ    ‚îÇ   ‚îÇ    ‚îÇ       ‚îÇ    ‚îî {}\n             ‚îÇ    ‚îÇ   ‚îÇ    ‚îÇ       ‚îî <concurrent.futures.thread._WorkItem object at 0x74371bc20680>\n             ‚îÇ    ‚îÇ   ‚îÇ    ‚îî (<function _unary_response_in_pool at 0x74371bc2d120>, <grpc._cython.cygrpc.RequestCallEvent object at 0x74371bc1b290>, <grpc...\n             ‚îÇ    ‚îÇ   ‚îî <concurrent.futures.thread._WorkItem object at 0x74371bc20680>\n             ‚îÇ    ‚îî <built-in method run of _contextvars.Context object at 0x74371c3d2c00>\n             ‚îî <concurrent.futures.thread._WorkItem object at 0x74371bc20680>\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/.venv/lib/python3.12/site-packages/grpc/_server.py\", line 793, in _unary_response_in_pool\n    response, proceed = _call_behavior(\n                        ‚îî <function _call_behavior at 0x74371bc2ccc0>\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/.venv/lib/python3.12/site-packages/grpc/_server.py\", line 610, in _call_behavior\n    response_or_iterator = behavior(argument, context)\n                           ‚îÇ        ‚îÇ         ‚îî <grpc._server._Context object at 0x74371bc20890>\n                           ‚îÇ        ‚îî expression: \"(23+44^2*2/33)+22\"\n                           ‚îÇ          \n                           ‚îî <bound method gRPC_math_solve.Solve of <__main__.gRPC_math_solve object at 0x74371cae5fa0>>\n\n> File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 168, in Solve\n    MathAnswer = MathSolver.SolveExpression(MathSolver, request)\n                 ‚îÇ          ‚îÇ               ‚îÇ           ‚îî expression: \"(23+44^2*2/33)+22\"\n                 ‚îÇ          ‚îÇ               ‚îÇ             \n                 ‚îÇ          ‚îÇ               ‚îî <class '__main__.MathSolver'>\n                 ‚îÇ          ‚îî <function MathSolver.SolveExpression at 0x74371bd42d40>\n                 ‚îî <class '__main__.MathSolver'>\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 113, in SolveExpression\n    if self._is_equation(parsed):\n       ‚îÇ    ‚îÇ            ‚îî 22 + 23 + (44**2*2)/33\n       ‚îÇ    ‚îî <function MathSolver._is_equation at 0x74371bd40c20>\n       ‚îî <class '__main__.MathSolver'>\n\nTypeError: MathSolver._is_equation() missing 1 required positional argument: 'expr'\n", "record": {"elapsed": {"repr": "0:00:02.459791", "seconds": 2.459791}, "exception": {"type": "TypeError", "value": "MathSolver._is_equation() missing 1 required positional argument: 'expr'", "traceback": true}, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "Solve", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 168, "message": "An error has been caught in function 'Solve', process 'MainProcess' (399592), thread 'ThreadPoolExecutor-0_0' (127778431170240):", "module": "service_math_solve", "name": "__main__", "process": {"id": 399592, "name": "MainProcess"}, "thread": {"id": 127778431170240, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 15:01:51.615308+07:00", "timestamp": 1748419311.615308}}}
{"text": "2025-05-28T15:02:51.787416+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.256505", "seconds": 0.256505}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 195, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 399670, "name": "MainProcess"}, "thread": {"id": 137183388110976, "name": "MainThread"}, "time": {"repr": "2025-05-28 15:02:51.787416+07:00", "timestamp": 1748419371.787416}}}
{"text": "2025-05-28T15:02:54.424901+0700 INFO Method \"Solve\" has called from  |  ipv4:127.0.0.1:52362\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}\n", "record": {"elapsed": {"repr": "0:00:02.893990", "seconds": 2.89399}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 132, "message": "Method \"Solve\" has called from  |  ipv4:127.0.0.1:52362\n{\n    \"expression\": \"(23+44^2*2/33)+22\"\n}", "module": "service_math_solve", "name": "__main__", "process": {"id": 399670, "name": "MainProcess"}, "thread": {"id": 137182035560128, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 15:02:54.424901+07:00", "timestamp": 1748419374.424901}}}
{"text": "2025-05-28T15:02:54.483282+0700 DEBUG Checking if 22 + 23 + (44**2*2)/33 is an equation...\n", "record": {"elapsed": {"repr": "0:00:02.952371", "seconds": 2.952371}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_is_equation", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 98, "message": "Checking if 22 + 23 + (44**2*2)/33 is an equation...", "module": "service_math_solve", "name": "__main__", "process": {"id": 399670, "name": "MainProcess"}, "thread": {"id": 137182035560128, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 15:02:54.483282+07:00", "timestamp": 1748419374.483282}}}
{"text": "2025-05-28T15:02:54.483839+0700 DEBUG 22 + 23 + (44**2*2)/33 is not an equation.\n", "record": {"elapsed": {"repr": "0:00:02.952928", "seconds": 2.952928}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_is_equation", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 105, "message": "22 + 23 + (44**2*2)/33 is not an equation.", "module": "service_math_solve", "name": "__main__", "process": {"id": 399670, "name": "MainProcess"}, "thread": {"id": 137182035560128, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-05-28 15:02:54.483839+07:00", "timestamp": 1748419374.483839}}}
