{"text": "2025-06-01T20:57:17.248240+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.377987", "seconds": 0.377987}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 208, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 635352, "name": "MainProcess"}, "thread": {"id": 124432132882560, "name": "MainThread"}, "time": {"repr": "2025-06-01 20:57:17.248240+07:00", "timestamp": 1748786237.24824}}}
{"text": "2025-06-01T21:20:43.341517+0700 INFO Method \"Solve\" has called from  |  ipv4:127.0.0.1:45910\n{\n    \"expression\": \"4^5\"\n}\n", "record": {"elapsed": {"repr": "0:23:26.471264", "seconds": 1406.471264}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 136, "message": "Method \"Solve\" has called from  |  ipv4:127.0.0.1:45910\n{\n    \"expression\": \"4^5\"\n}", "module": "service_math_solve", "name": "__main__", "process": {"id": 635352, "name": "MainProcess"}, "thread": {"id": 124430923568832, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-06-01 21:20:43.341517+07:00", "timestamp": 1748787643.341517}}}
{"text": "2025-06-01T21:20:43.358565+0700 DEBUG Checking if 4**5 is an equation...\n", "record": {"elapsed": {"repr": "0:23:26.488312", "seconds": 1406.488312}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_is_equation", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 100, "message": "Checking if 4**5 is an equation...", "module": "service_math_solve", "name": "__main__", "process": {"id": 635352, "name": "MainProcess"}, "thread": {"id": 124430923568832, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-06-01 21:20:43.358565+07:00", "timestamp": 1748787643.358565}}}
{"text": "2025-06-01T21:20:43.358895+0700 DEBUG 4**5 is not an equation.\n", "record": {"elapsed": {"repr": "0:23:26.488642", "seconds": 1406.488642}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_is_equation", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 107, "message": "4**5 is not an equation.", "module": "service_math_solve", "name": "__main__", "process": {"id": 635352, "name": "MainProcess"}, "thread": {"id": 124430923568832, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-06-01 21:20:43.358895+07:00", "timestamp": 1748787643.358895}}}
{"text": "2025-06-01T21:20:49.620392+0700 INFO Method \"Metadata\" has called from  |  ipv4:127.0.0.1:45910\n{}\n", "record": {"elapsed": {"repr": "0:23:32.750139", "seconds": 1412.750139}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 136, "message": "Method \"Metadata\" has called from  |  ipv4:127.0.0.1:45910\n{}", "module": "service_math_solve", "name": "__main__", "process": {"id": 635352, "name": "MainProcess"}, "thread": {"id": 124430923568832, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-06-01 21:20:49.620392+07:00", "timestamp": 1748787649.620392}}}
{"text": "2025-06-01T21:21:14.951251+0700 INFO Method \"Solve\" has called from  |  ipv4:127.0.0.1:39228\n{\n    \"expression\": \"3+2\"\n}\n", "record": {"elapsed": {"repr": "0:23:58.080998", "seconds": 1438.080998}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 136, "message": "Method \"Solve\" has called from  |  ipv4:127.0.0.1:39228\n{\n    \"expression\": \"3+2\"\n}", "module": "service_math_solve", "name": "__main__", "process": {"id": 635352, "name": "MainProcess"}, "thread": {"id": 124430923568832, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-06-01 21:21:14.951251+07:00", "timestamp": 1748787674.951251}}}
{"text": "2025-06-01T21:21:14.962613+0700 DEBUG Checking if 2 + 3 is an equation...\n", "record": {"elapsed": {"repr": "0:23:58.092360", "seconds": 1438.09236}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_is_equation", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 100, "message": "Checking if 2 + 3 is an equation...", "module": "service_math_solve", "name": "__main__", "process": {"id": 635352, "name": "MainProcess"}, "thread": {"id": 124430923568832, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-06-01 21:21:14.962613+07:00", "timestamp": 1748787674.962613}}}
{"text": "2025-06-01T21:21:14.962925+0700 DEBUG 2 + 3 is not an equation.\n", "record": {"elapsed": {"repr": "0:23:58.092672", "seconds": 1438.092672}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_is_equation", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 107, "message": "2 + 3 is not an equation.", "module": "service_math_solve", "name": "__main__", "process": {"id": 635352, "name": "MainProcess"}, "thread": {"id": 124430923568832, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-06-01 21:21:14.962925+07:00", "timestamp": 1748787674.962925}}}
{"text": "2025-06-01T21:34:09.741060+0700 ERROR Failed to download proto file: 'GithubProtoDownLoader' object has no attribute '_GithubProtoDownLoader__repo_url'\n", "record": {"elapsed": {"repr": "0:00:00.259623", "seconds": 0.259623}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "download_proto", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 113, "message": "Failed to download proto file: 'GithubProtoDownLoader' object has no attribute '_GithubProtoDownLoader__repo_url'", "module": "service_math_solve", "name": "__main__", "process": {"id": 653983, "name": "MainProcess"}, "thread": {"id": 137183164145792, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:34:09.741060+07:00", "timestamp": 1748788449.74106}}}
{"text": "2025-06-01T21:34:09.741408+0700 ERROR An error has been caught in function 'RUN_MATH_SOLVE_SERVICE', process 'MainProcess' (653983), thread 'MainThread' (137183164145792):\nTraceback (most recent call last):\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 244, in <module>\n    RUN_MATH_SOLVE_SERVICE()\n    ‚îî <function RUN_MATH_SOLVE_SERVICE at 0x7cc4709ddf80>\n\n> File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 222, in RUN_MATH_SOLVE_SERVICE\n    GithubProtoDownLoader().download_proto()\n    ‚îî <class '__main__.GithubProtoDownLoader'>\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 104, in download_proto\n    repo = git.Repo.clone_from(self.__repo_url, temp_folder, branch='master', depth=1)\n           ‚îÇ   ‚îÇ    ‚îÇ          ‚îÇ                ‚îî '/tmp/tmp32574nil'\n           ‚îÇ   ‚îÇ    ‚îÇ          ‚îî <__main__.GithubProtoDownLoader object at 0x7cc46d242e70>\n           ‚îÇ   ‚îÇ    ‚îî <classmethod(<function Repo.clone_from at 0x7cc46e9af6a0>)>\n           ‚îÇ   ‚îî <class 'git.repo.base.Repo'>\n           ‚îî <module 'git' from '/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/.venv/lib/python3.12/site-packages/git/__init__.py'>\n\nAttributeError: 'GithubProtoDownLoader' object has no attribute '_GithubProtoDownLoader__repo_url'. Did you mean: '_GithubProtoDownLoader__config'?\n", "record": {"elapsed": {"repr": "0:00:00.259971", "seconds": 0.259971}, "exception": {"type": "AttributeError", "value": "'GithubProtoDownLoader' object has no attribute '_GithubProtoDownLoader__repo_url'", "traceback": true}, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 222, "message": "An error has been caught in function 'RUN_MATH_SOLVE_SERVICE', process 'MainProcess' (653983), thread 'MainThread' (137183164145792):", "module": "service_math_solve", "name": "__main__", "process": {"id": 653983, "name": "MainProcess"}, "thread": {"id": 137183164145792, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:34:09.741408+07:00", "timestamp": 1748788449.741408}}}
{"text": "2025-06-01T21:34:09.746258+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.264821", "seconds": 0.264821}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 237, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 653983, "name": "MainProcess"}, "thread": {"id": 137183164145792, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:34:09.746258+07:00", "timestamp": 1748788449.746258}}}
{"text": "2025-06-01T21:34:57.453218+0700 ERROR Failed to download proto file: Cmd('git') failed due to: exit code(128)\n  cmdline: git clone -v --branch=master --depth=1 -- https://github.com/dagahan/EyeMath_protos/tree/master/py /tmp/tmpt722jb55\n  stderr: 'Cloning into '/tmp/tmpt722jb55'...\nfatal: repository 'https://github.com/dagahan/EyeMath_protos/tree/master/py/' not found\n'\n", "record": {"elapsed": {"repr": "0:00:01.799912", "seconds": 1.799912}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "download_proto", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 113, "message": "Failed to download proto file: Cmd('git') failed due to: exit code(128)\n  cmdline: git clone -v --branch=master --depth=1 -- https://github.com/dagahan/EyeMath_protos/tree/master/py /tmp/tmpt722jb55\n  stderr: 'Cloning into '/tmp/tmpt722jb55'...\nfatal: repository 'https://github.com/dagahan/EyeMath_protos/tree/master/py/' not found\n'", "module": "service_math_solve", "name": "__main__", "process": {"id": 654062, "name": "MainProcess"}, "thread": {"id": 125655096893568, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:34:57.453218+07:00", "timestamp": 1748788497.453218}}}
{"text": "2025-06-01T21:34:57.453601+0700 ERROR An error has been caught in function 'RUN_MATH_SOLVE_SERVICE', process 'MainProcess' (654062), thread 'MainThread' (125655096893568):\nTraceback (most recent call last):\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 244, in <module>\n    RUN_MATH_SOLVE_SERVICE()\n    ‚îî <function RUN_MATH_SOLVE_SERVICE at 0x72485a41df80>\n\n> File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 222, in RUN_MATH_SOLVE_SERVICE\n    GithubProtoDownLoader().download_proto()\n    ‚îî <class '__main__.GithubProtoDownLoader'>\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 104, in download_proto\n    repo = git.Repo.clone_from(self.__repo_url, temp_folder, branch='master', depth=1)\n           ‚îÇ   ‚îÇ    ‚îÇ          ‚îÇ                ‚îî '/tmp/tmpt722jb55'\n           ‚îÇ   ‚îÇ    ‚îÇ          ‚îî <__main__.GithubProtoDownLoader object at 0x7248569b6c90>\n           ‚îÇ   ‚îÇ    ‚îî <classmethod(<function Repo.clone_from at 0x7248585076a0>)>\n           ‚îÇ   ‚îî <class 'git.repo.base.Repo'>\n           ‚îî <module 'git' from '/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/.venv/lib/python3.12/site-packages/git/__init__.py'>\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/.venv/lib/python3.12/site-packages/git/repo/base.py\", line 1541, in clone_from\n    return cls._clone(\n           ‚îÇ   ‚îî <classmethod(<function Repo._clone at 0x724858507560>)>\n           ‚îî <class 'git.repo.base.Repo'>\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/.venv/lib/python3.12/site-packages/git/repo/base.py\", line 1412, in _clone\n    finalize_process(proc, stderr=stderr)\n    ‚îÇ                ‚îÇ            ‚îî \"Cloning into '/tmp/tmpt722jb55'...\\nfatal: repository 'https://github.com/dagahan/EyeMath_protos/tree/master/py/' not found\\n\"\n    ‚îÇ                ‚îî <git.cmd.Git.AutoInterrupt object at 0x72485779e100>\n    ‚îî <function finalize_process at 0x7248585a8680>\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/.venv/lib/python3.12/site-packages/git/util.py\", line 504, in finalize_process\n    proc.wait(**kwargs)\n    ‚îÇ    ‚îÇ      ‚îî {'stderr': \"Cloning into '/tmp/tmpt722jb55'...\\nfatal: repository 'https://github.com/dagahan/EyeMath_protos/tree/master/py/'...\n    ‚îÇ    ‚îî <function Git.AutoInterrupt.wait at 0x724858615f80>\n    ‚îî <git.cmd.Git.AutoInterrupt object at 0x72485779e100>\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/.venv/lib/python3.12/site-packages/git/cmd.py\", line 834, in wait\n    raise GitCommandError(remove_password_if_present(self.args), status, errstr)\n          ‚îÇ               ‚îÇ                          ‚îÇ    ‚îÇ      ‚îÇ       ‚îî b\"Cloning into '/tmp/tmpt722jb55'...\\nfatal: repository 'https://github.com/dagahan/EyeMath_protos/tree/master/py/' not found\\n\"\n          ‚îÇ               ‚îÇ                          ‚îÇ    ‚îÇ      ‚îî 128\n          ‚îÇ               ‚îÇ                          ‚îÇ    ‚îî <member 'args' of 'AutoInterrupt' objects>\n          ‚îÇ               ‚îÇ                          ‚îî <git.cmd.Git.AutoInterrupt object at 0x72485779e100>\n          ‚îÇ               ‚îî <function remove_password_if_present at 0x7248585a89a0>\n          ‚îî <class 'git.exc.GitCommandError'>\n\ngit.exc.GitCommandError: Cmd('git') failed due to: exit code(128)\n  cmdline: git clone -v --branch=master --depth=1 -- https://github.com/dagahan/EyeMath_protos/tree/master/py /tmp/tmpt722jb55\n  stderr: 'Cloning into '/tmp/tmpt722jb55'...\nfatal: repository 'https://github.com/dagahan/EyeMath_protos/tree/master/py/' not found\n'\n", "record": {"elapsed": {"repr": "0:00:01.800295", "seconds": 1.800295}, "exception": {"type": "GitCommandError", "value": "Cmd('git') failed due to: exit code(128)\n  cmdline: git clone -v --branch=master --depth=1 -- https://github.com/dagahan/EyeMath_protos/tree/master/py /tmp/tmpt722jb55\n  stderr: 'Cloning into '/tmp/tmpt722jb55'...\nfatal: repository 'https://github.com/dagahan/EyeMath_protos/tree/master/py/' not found\n'", "traceback": true}, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 222, "message": "An error has been caught in function 'RUN_MATH_SOLVE_SERVICE', process 'MainProcess' (654062), thread 'MainThread' (125655096893568):", "module": "service_math_solve", "name": "__main__", "process": {"id": 654062, "name": "MainProcess"}, "thread": {"id": 125655096893568, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:34:57.453601+07:00", "timestamp": 1748788497.453601}}}
{"text": "2025-06-01T21:34:57.460537+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:01.807231", "seconds": 1.807231}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 237, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 654062, "name": "MainProcess"}, "thread": {"id": 125655096893568, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:34:57.460537+07:00", "timestamp": 1748788497.460537}}}
{"text": "2025-06-01T21:35:24.125114+0700 ERROR Failed to download proto file: 'GithubProtoDownLoader' object has no attribute '_GithubProtoDownLoader__proto_path'\n", "record": {"elapsed": {"repr": "0:00:01.717622", "seconds": 1.717622}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "download_proto", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 113, "message": "Failed to download proto file: 'GithubProtoDownLoader' object has no attribute '_GithubProtoDownLoader__proto_path'", "module": "service_math_solve", "name": "__main__", "process": {"id": 654145, "name": "MainProcess"}, "thread": {"id": 126512692965504, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:35:24.125114+07:00", "timestamp": 1748788524.125114}}}
{"text": "2025-06-01T21:35:24.125447+0700 ERROR An error has been caught in function 'RUN_MATH_SOLVE_SERVICE', process 'MainProcess' (654145), thread 'MainThread' (126512692965504):\nTraceback (most recent call last):\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 244, in <module>\n    RUN_MATH_SOLVE_SERVICE()\n    ‚îî <function RUN_MATH_SOLVE_SERVICE at 0x731006f21f80>\n\n> File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 222, in RUN_MATH_SOLVE_SERVICE\n    GithubProtoDownLoader().download_proto()\n    ‚îî <class '__main__.GithubProtoDownLoader'>\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 105, in download_proto\n    proto_file_path = os.path.join(repo.working_tree_dir, self.__proto_path)\n                      ‚îÇ  ‚îÇ    ‚îÇ    ‚îÇ    ‚îÇ                 ‚îî <__main__.GithubProtoDownLoader object at 0x73100421c950>\n                      ‚îÇ  ‚îÇ    ‚îÇ    ‚îÇ    ‚îî <property object at 0x731004f8b5b0>\n                      ‚îÇ  ‚îÇ    ‚îÇ    ‚îî <git.repo.base.Repo '/tmp/tmpzq9gbf6n/.git'>\n                      ‚îÇ  ‚îÇ    ‚îî <function join at 0x731006f18c20>\n                      ‚îÇ  ‚îî <module 'posixpath' (frozen)>\n                      ‚îî <module 'os' (frozen)>\n\nAttributeError: 'GithubProtoDownLoader' object has no attribute '_GithubProtoDownLoader__proto_path'. Did you mean: '_GithubProtoDownLoader__repo_url'?\n", "record": {"elapsed": {"repr": "0:00:01.717955", "seconds": 1.717955}, "exception": {"type": "AttributeError", "value": "'GithubProtoDownLoader' object has no attribute '_GithubProtoDownLoader__proto_path'", "traceback": true}, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 222, "message": "An error has been caught in function 'RUN_MATH_SOLVE_SERVICE', process 'MainProcess' (654145), thread 'MainThread' (126512692965504):", "module": "service_math_solve", "name": "__main__", "process": {"id": 654145, "name": "MainProcess"}, "thread": {"id": 126512692965504, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:35:24.125447+07:00", "timestamp": 1748788524.125447}}}
{"text": "2025-06-01T21:35:24.130432+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:01.722940", "seconds": 1.72294}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 237, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 654145, "name": "MainProcess"}, "thread": {"id": 126512692965504, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:35:24.130432+07:00", "timestamp": 1748788524.130432}}}
{"text": "2025-06-01T21:36:06.860420+0700 ERROR Failed to download proto file: 'str' object is not callable\n", "record": {"elapsed": {"repr": "0:00:01.528871", "seconds": 1.528871}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "download_proto", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 113, "message": "Failed to download proto file: 'str' object is not callable", "module": "service_math_solve", "name": "__main__", "process": {"id": 654230, "name": "MainProcess"}, "thread": {"id": 139145277005952, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:36:06.860420+07:00", "timestamp": 1748788566.86042}}}
{"text": "2025-06-01T21:36:06.860771+0700 ERROR An error has been caught in function 'RUN_MATH_SOLVE_SERVICE', process 'MainProcess' (654230), thread 'MainThread' (139145277005952):\nTraceback (most recent call last):\n\n  File \"/usr/lib/python3.12/shutil.py\", line 886, in move\n    os.rename(src, real_dst)\n    ‚îÇ  ‚îÇ      ‚îÇ    ‚îî 'service_math_solve_pb2_grpc.py'\n    ‚îÇ  ‚îÇ      ‚îî '/tmp/tmpc9lq3szf/external_api_gateway_pb2.py/external_api_gateway_pb2_grpc.py/external_api_gateway_pb2_grpc.py/service_math_...\n    ‚îÇ  ‚îî <built-in function rename>\n    ‚îî <module 'os' (frozen)>\n\nFileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc9lq3szf/external_api_gateway_pb2.py/external_api_gateway_pb2_grpc.py/external_api_gateway_pb2_grpc.py/service_math_solve_pb2.py' -> 'service_math_solve_pb2_grpc.py'\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 244, in <module>\n    RUN_MATH_SOLVE_SERVICE()\n    ‚îî <function RUN_MATH_SOLVE_SERVICE at 0x7e8d47a1df80>\n\n> File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 222, in RUN_MATH_SOLVE_SERVICE\n    GithubProtoDownLoader().download_proto()\n    ‚îî <class '__main__.GithubProtoDownLoader'>\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 106, in download_proto\n    shutil.move(os.path.join(temp_folder, 'external_api_gateway_pb2.py',\n    ‚îÇ      ‚îÇ    ‚îÇ  ‚îÇ    ‚îÇ    ‚îî '/tmp/tmpc9lq3szf'\n    ‚îÇ      ‚îÇ    ‚îÇ  ‚îÇ    ‚îî <function join at 0x7e8d47a14c20>\n    ‚îÇ      ‚îÇ    ‚îÇ  ‚îî <module 'posixpath' (frozen)>\n    ‚îÇ      ‚îÇ    ‚îî <module 'os' (frozen)>\n    ‚îÇ      ‚îî <function move at 0x7e8d45d3b380>\n    ‚îî <module 'shutil' from '/usr/lib/python3.12/shutil.py'>\n\n  File \"/usr/lib/python3.12/shutil.py\", line 906, in move\n    copy_function(src, real_dst)\n    ‚îÇ             ‚îÇ    ‚îî 'service_math_solve_pb2_grpc.py'\n    ‚îÇ             ‚îî '/tmp/tmpc9lq3szf/external_api_gateway_pb2.py/external_api_gateway_pb2_grpc.py/external_api_gateway_pb2_grpc.py/service_math_...\n    ‚îî '.'\n\nTypeError: 'str' object is not callable\n", "record": {"elapsed": {"repr": "0:00:01.529222", "seconds": 1.529222}, "exception": {"type": "TypeError", "value": "'str' object is not callable", "traceback": true}, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 222, "message": "An error has been caught in function 'RUN_MATH_SOLVE_SERVICE', process 'MainProcess' (654230), thread 'MainThread' (139145277005952):", "module": "service_math_solve", "name": "__main__", "process": {"id": 654230, "name": "MainProcess"}, "thread": {"id": 139145277005952, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:36:06.860771+07:00", "timestamp": 1748788566.860771}}}
{"text": "2025-06-01T21:36:06.865955+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:01.534406", "seconds": 1.534406}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 237, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 654230, "name": "MainProcess"}, "thread": {"id": 139145277005952, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:36:06.865955+07:00", "timestamp": 1748788566.865955}}}
{"text": "2025-06-01T21:46:36.515175+0700 CRITICAL Service crashed: name 'GithubProtoDownloader' is not defined\n", "record": {"elapsed": {"repr": "0:00:00.259734", "seconds": 0.259734}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "<module>", "level": {"icon": "‚ò†Ô∏è", "name": "CRITICAL", "no": 50}, "line": 256, "message": "Service crashed: name 'GithubProtoDownloader' is not defined", "module": "service_math_solve", "name": "__main__", "process": {"id": 654507, "name": "MainProcess"}, "thread": {"id": 132627056857216, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:46:36.515175+07:00", "timestamp": 1748789196.515175}}}
{"text": "2025-06-01T21:47:47.761864+0700 ERROR Failed to download proto file: name 'destination' is not defined\n", "record": {"elapsed": {"repr": "0:00:01.879969", "seconds": 1.879969}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "download_proto", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 122, "message": "Failed to download proto file: name 'destination' is not defined", "module": "service_math_solve", "name": "__main__", "process": {"id": 654550, "name": "MainProcess"}, "thread": {"id": 124337140936832, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:47:47.761864+07:00", "timestamp": 1748789267.761864}}}
{"text": "2025-06-01T21:47:47.762237+0700 ERROR An error has been caught in function 'RUN_MATH_SOLVE_SERVICE', process 'MainProcess' (654550), thread 'MainThread' (124337140936832):\nTraceback (most recent call last):\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 254, in <module>\n    RUN_MATH_SOLVE_SERVICE()\n    ‚îî <function RUN_MATH_SOLVE_SERVICE at 0x71157df21f80>\n\n> File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 232, in RUN_MATH_SOLVE_SERVICE\n    proto_downloader().download_proto()\n    ‚îî <class '__main__.GithubProtoDownloader'>\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 117, in download_proto\n    shutil.move(src_path, os.path.join(destination, entry))\n    ‚îÇ      ‚îÇ    ‚îÇ         ‚îÇ  ‚îÇ    ‚îÇ                 ‚îî 'service_math_solve_pb2.py'\n    ‚îÇ      ‚îÇ    ‚îÇ         ‚îÇ  ‚îÇ    ‚îî <function join at 0x71157df18c20>\n    ‚îÇ      ‚îÇ    ‚îÇ         ‚îÇ  ‚îî <module 'posixpath' (frozen)>\n    ‚îÇ      ‚îÇ    ‚îÇ         ‚îî <module 'os' (frozen)>\n    ‚îÇ      ‚îÇ    ‚îî '/tmp/tmp9z_kl96x/py/service_math_solve_pb2.py'\n    ‚îÇ      ‚îî <function move at 0x71157c13f380>\n    ‚îî <module 'shutil' from '/usr/lib/python3.12/shutil.py'>\n\nNameError: name 'destination' is not defined\n", "record": {"elapsed": {"repr": "0:00:01.880342", "seconds": 1.880342}, "exception": {"type": "NameError", "value": "name 'destination' is not defined", "traceback": true}, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 232, "message": "An error has been caught in function 'RUN_MATH_SOLVE_SERVICE', process 'MainProcess' (654550), thread 'MainThread' (124337140936832):", "module": "service_math_solve", "name": "__main__", "process": {"id": 654550, "name": "MainProcess"}, "thread": {"id": 124337140936832, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:47:47.762237+07:00", "timestamp": 1748789267.762237}}}
{"text": "2025-06-01T21:47:47.767184+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:01.885289", "seconds": 1.885289}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 247, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 654550, "name": "MainProcess"}, "thread": {"id": 124337140936832, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:47:47.767184+07:00", "timestamp": 1748789267.767184}}}
{"text": "2025-06-01T21:48:36.218660+0700 ERROR Failed to download proto file: name '_GithubProtoDownloader__destination' is not defined\n", "record": {"elapsed": {"repr": "0:00:01.902755", "seconds": 1.902755}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "download_proto", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 123, "message": "Failed to download proto file: name '_GithubProtoDownloader__destination' is not defined", "module": "service_math_solve", "name": "__main__", "process": {"id": 654659, "name": "MainProcess"}, "thread": {"id": 138172151492736, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:48:36.218660+07:00", "timestamp": 1748789316.21866}}}
{"text": "2025-06-01T21:48:36.219056+0700 ERROR An error has been caught in function 'RUN_MATH_SOLVE_SERVICE', process 'MainProcess' (654659), thread 'MainThread' (138172151492736):\nTraceback (most recent call last):\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 255, in <module>\n    RUN_MATH_SOLVE_SERVICE()\n    ‚îî <function RUN_MATH_SOLVE_SERVICE at 0x7daab4dbdf80>\n\n> File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 233, in RUN_MATH_SOLVE_SERVICE\n    proto_downloader().download_proto()\n    ‚îî <class '__main__.GithubProtoDownloader'>\n\n  File \"/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py\", line 118, in download_proto\n    shutil.move(src_path, os.path.join(__destination, entry))\n    ‚îÇ      ‚îÇ    ‚îÇ         ‚îÇ  ‚îÇ    ‚îÇ                   ‚îî 'service_math_solve_pb2.py'\n    ‚îÇ      ‚îÇ    ‚îÇ         ‚îÇ  ‚îÇ    ‚îî <function join at 0x7daab4db4c20>\n    ‚îÇ      ‚îÇ    ‚îÇ         ‚îÇ  ‚îî <module 'posixpath' (frozen)>\n    ‚îÇ      ‚îÇ    ‚îÇ         ‚îî <module 'os' (frozen)>\n    ‚îÇ      ‚îÇ    ‚îî '/tmp/tmpp4pz79j9/py/service_math_solve_pb2.py'\n    ‚îÇ      ‚îî <function move at 0x7daab2f4b380>\n    ‚îî <module 'shutil' from '/usr/lib/python3.12/shutil.py'>\n\nNameError: name '_GithubProtoDownloader__destination' is not defined\n", "record": {"elapsed": {"repr": "0:00:01.903151", "seconds": 1.903151}, "exception": {"type": "NameError", "value": "name '_GithubProtoDownloader__destination' is not defined", "traceback": true}, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ùå", "name": "ERROR", "no": 40}, "line": 233, "message": "An error has been caught in function 'RUN_MATH_SOLVE_SERVICE', process 'MainProcess' (654659), thread 'MainThread' (138172151492736):", "module": "service_math_solve", "name": "__main__", "process": {"id": 654659, "name": "MainProcess"}, "thread": {"id": 138172151492736, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:48:36.219056+07:00", "timestamp": 1748789316.219056}}}
{"text": "2025-06-01T21:48:36.224114+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:01.908209", "seconds": 1.908209}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 248, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 654659, "name": "MainProcess"}, "thread": {"id": 138172151492736, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:48:36.224114+07:00", "timestamp": 1748789316.224114}}}
{"text": "2025-06-01T21:49:14.089890+0700 INFO –£—Å–ø–µ—à–Ω–æ —Å–∫–∞—á–∞–Ω—ã –∏ –ø–µ—Ä–µ–º–µ—â–µ–Ω—ã —Ñ–∞–π–ª—ã –∏–∑ py –≤ .\n", "record": {"elapsed": {"repr": "0:00:01.887657", "seconds": 1.887657}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "download_proto", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 121, "message": "–£—Å–ø–µ—à–Ω–æ —Å–∫–∞—á–∞–Ω—ã –∏ –ø–µ—Ä–µ–º–µ—â–µ–Ω—ã —Ñ–∞–π–ª—ã –∏–∑ py –≤ .", "module": "service_math_solve", "name": "__main__", "process": {"id": 654746, "name": "MainProcess"}, "thread": {"id": 134175935393920, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:49:14.089890+07:00", "timestamp": 1748789354.08989}}}
{"text": "2025-06-01T21:49:14.094142+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:01.891909", "seconds": 1.891909}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 248, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 654746, "name": "MainProcess"}, "thread": {"id": 134175935393920, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:49:14.094142+07:00", "timestamp": 1748789354.094142}}}
{"text": "2025-06-01T21:49:35.056316+0700 INFO –£—Å–ø–µ—à–Ω–æ —Å–∫–∞—á–∞–Ω—ã –∏ –ø–µ—Ä–µ–º–µ—â–µ–Ω—ã —Ñ–∞–π–ª—ã –∏–∑ py –≤ github_gen/\n", "record": {"elapsed": {"repr": "0:00:01.702797", "seconds": 1.702797}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "download_proto", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 121, "message": "–£—Å–ø–µ—à–Ω–æ —Å–∫–∞—á–∞–Ω—ã –∏ –ø–µ—Ä–µ–º–µ—â–µ–Ω—ã —Ñ–∞–π–ª—ã –∏–∑ py –≤ github_gen/", "module": "service_math_solve", "name": "__main__", "process": {"id": 654834, "name": "MainProcess"}, "thread": {"id": 125876819411072, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:49:35.056316+07:00", "timestamp": 1748789375.056316}}}
{"text": "2025-06-01T21:49:35.060920+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:01.707401", "seconds": 1.707401}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 248, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 654834, "name": "MainProcess"}, "thread": {"id": 125876819411072, "name": "MainThread"}, "time": {"repr": "2025-06-01 21:49:35.060920+07:00", "timestamp": 1748789375.06092}}}
{"text": "2025-06-02T01:47:11.023558+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.264467", "seconds": 0.264467}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 252, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 671379, "name": "MainProcess"}, "thread": {"id": 138164403712128, "name": "MainThread"}, "time": {"repr": "2025-06-02 01:47:11.023558+07:00", "timestamp": 1748803631.023558}}}
{"text": "2025-06-02T01:47:54.349131+0700 INFO Method \"Solve\" has called from  |  ipv4:127.0.0.1:34120\n{\n    \"expression\": \"4^5\"\n}\n", "record": {"elapsed": {"repr": "0:00:43.590040", "seconds": 43.59004}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_logrequest", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 180, "message": "Method \"Solve\" has called from  |  ipv4:127.0.0.1:34120\n{\n    \"expression\": \"4^5\"\n}", "module": "service_math_solve", "name": "__main__", "process": {"id": 671379, "name": "MainProcess"}, "thread": {"id": 138162848392896, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-06-02 01:47:54.349131+07:00", "timestamp": 1748803674.349131}}}
{"text": "2025-06-02T01:47:54.365869+0700 DEBUG Checking if 4**5 is an equation...\n", "record": {"elapsed": {"repr": "0:00:43.606778", "seconds": 43.606778}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_is_equation", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 144, "message": "Checking if 4**5 is an equation...", "module": "service_math_solve", "name": "__main__", "process": {"id": 671379, "name": "MainProcess"}, "thread": {"id": 138162848392896, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-06-02 01:47:54.365869+07:00", "timestamp": 1748803674.365869}}}
{"text": "2025-06-02T01:47:54.366337+0700 DEBUG 4**5 is not an equation.\n", "record": {"elapsed": {"repr": "0:00:43.607246", "seconds": 43.607246}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "_is_equation", "level": {"icon": "üêû", "name": "DEBUG", "no": 10}, "line": 151, "message": "4**5 is not an equation.", "module": "service_math_solve", "name": "__main__", "process": {"id": 671379, "name": "MainProcess"}, "thread": {"id": 138162848392896, "name": "ThreadPoolExecutor-0_0"}, "time": {"repr": "2025-06-02 01:47:54.366337+07:00", "timestamp": 1748803674.366337}}}
{"text": "2025-06-02T02:04:05.673864+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.273003", "seconds": 0.273003}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 207, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 672973, "name": "MainProcess"}, "thread": {"id": 134203601092736, "name": "MainThread"}, "time": {"repr": "2025-06-02 02:04:05.673864+07:00", "timestamp": 1748804645.673864}}}
{"text": "2025-06-02T02:08:41.262105+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.260651", "seconds": 0.260651}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 207, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 673888, "name": "MainProcess"}, "thread": {"id": 128732188897408, "name": "MainThread"}, "time": {"repr": "2025-06-02 02:08:41.262105+07:00", "timestamp": 1748804921.262105}}}
{"text": "2025-06-02T02:17:26.387749+0700 INFO gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001\n", "record": {"elapsed": {"repr": "0:00:00.260422", "seconds": 0.260422}, "exception": null, "extra": {}, "file": {"name": "service_math_solve.py", "path": "/home/usov/myprojects/EyeMath/SERVICE_MATH_SOLVE/service_math_solve.py"}, "function": "RUN_MATH_SOLVE_SERVICE", "level": {"icon": "‚ÑπÔ∏è", "name": "INFO", "no": 20}, "line": 207, "message": "gRPC —Å–µ—Ä–≤–µ—Ä –∑–∞–ø—É—â–µ–Ω –Ω–∞ 0.0.0.0:8001", "module": "service_math_solve", "name": "__main__", "process": {"id": 675150, "name": "MainProcess"}, "thread": {"id": 132810007269504, "name": "MainThread"}, "time": {"repr": "2025-06-02 02:17:26.387749+07:00", "timestamp": 1748805446.387749}}}
